### ISSUE TITLE
iPhone: Chrome issues

### ISSUE THREAD

**Issue by willum070** [WorldWideTelescope/wwt-web-client#28] opened 2014-11-20 20:12 UTC
iOS 8.1: Chrome issues iPhone 5  iOS8.1 -  Chrome  *  The tracking and the share button in the upper left are on top of each other (see attached image) --  I somehow have gotten my Chrome in a state where that splash page comes up but never goes away.  You can see from the attached that the window underneath looks fine.  This may be me but I've flushed my cache and done everything except reinstall Chrome to see what is causing the page never to go away.

**Comment by kfogel** [comment] 2015-10-08 03:02
Removing the "Prio3" label -- as per phone call today with @patudom and @doctorspaceman, we'll use milestones for scheduling priority.  I'm not sure what milestone "Prio3" corresponded to, but if it's none of the currently-available milestones, please just create one and put this issue in it.

**Comment by thewebkid** [comment] 2015-10-19 18:35
This is a very old bug and I remember fixing it months ago in TFS. Is this really still an issue? Please confirm.

**Comment by doctorspaceman** [comment] 2015-10-19 18:41
I have checked this again and not sure why Eric reopened this on June 7.  But I can't reproduce the bug now.  I'm closing this one.

**Closed by doctorspaceman** 2015-10-19 18:41 UTC
Labels: bug
